[project]
name = "job-listing-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beanie>=2.0.0",
    "fastapi[standard]>=0.118.0",
    "motor>=3.7.1",
    "pymongo>=4.15.2",
]
